[private]
default:
  @just --list

compile:
  @cargo build --release

flash BIN='':
  @if [ ! "{{BIN}}" = '' ]; then \
    espflash flash {{BIN}} ; \
  else \
    cargo build --release ; \
    espflash flash ./target/xtensa-esp32-espidf/release/esp32cam_rs ; \
  fi

dev:
  @cargo run
