[private]
default:
  @just --list

compile:
  #!/bin/bash
  cd ./cmd/yolo_rs ; cargo build --release
  cd ./../../ ; pwd
  go build ./cmd/api

run: compile
  ./api

dev:
  #!/bin/bash
  cd ./cmd/yolo_rs ; cargo build --release
  cd ./../../ ; pwd
  go run ./cmd/api
