[private]
default:
  @just --list

compile:
  @cd ./cmd/api/lib/yolo_rs ; cargo build --release
  @go build ./cmd/api

run: compile
  ./api

dev:
  @cd ./cmd/api/lib/yolo_rs ; cargo build --release
  go run ./cmd/api
